Sprint 3
anikogo/middle.messenger.praktikum.yandex pull request #14
Opened 2022-07-15 20:30 UTC by anikogo

2022-07-16 18:07 UTC, ivan-infro commented
Необходимо настроить роутинг так, чтобы обновление страницы отображало то же самое состояние (сейчас если зайти на /settings и обновить страницу - 404 error)

2022-07-16 18:08 UTC, ivan-infro commented
Переключение между чатами приводит к дублированию сообщений

2022-07-16 18:09 UTC, ivan-infro commented
Созданный чат не появляется в списке (приходится обновлять страницу)

2022-07-16 18:09 UTC, ivan-infro commented
Необходимо добавить функционал редактирования участников чата

2022-07-16 18:10 UTC, ivan-infro commented
У пользователей, добавленных в чат, не работает кнопка удаления чата и не выводится никаких ошибок (у автора чата - работает)

2022-07-16 18:10 UTC, ivan-infro commented
На странице Settings должны отображаться текущией данные

2022-07-16 18:20 UTC, ivan-infro requested changes

2022-07-16 18:20 UTC, ivan-infro commented on src/components/DivButton.ts
> +export default class DivButton extends Block {
Использование div'ов вместо кнопок ухудшает a11y (accessibility) приложения. Старайтесь избегать такого подхода. В случаях, когда это по каким-то причинам невозможно, всегда указывайте у элемента свойство role https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role

2022-07-16 18:20 UTC, ivan-infro commented on src/components/IconButton.ts
> +//@ts-ignore
Старайтесь не использовать игнорирующие комментарии (ts-ignore, eslint-disable), это может привести к замалчиванию реальных ошибок

2022-07-16 18:20 UTC, ivan-infro commented on src/components/IconButton.ts
> +        ${octicons[this.props.Icon].toSVG()}
Если в props передать иконку, которой нет в octicons, то приложение упадет в runtime с ошибкой

2022-07-16 18:20 UTC, ivan-infro commented on src/modules/ChatMessage.ts
> +    super({...props});
В данном случае копирование объекта через деструктуризацию избыточно

2022-07-16 18:20 UTC, ivan-infro commented on src/modules/ChatModal.ts
> +    const result = await httptransport.get("https://ya-praktikum.tech/api/v2/chats?limit=30");
Константы необходимо выносить в отдельные переменные, или даже отдельные файлы (в данном случае лучше вынести url API из исходного кода компонента)

2022-07-16 18:20 UTC, ivan-infro commented on src/modules/ChatModal.ts
> +      const chats = JSON.parse(result.response);
Если в ответе придет не JSON, то приложение упадет с ошибкой. Парсинг данных, полученных из вне, особенно важно оборачивать в безопасные конструкции вида try...catch (или валидировать входные данные)

2022-07-16 18:20 UTC, ivan-infro commented on src/pages/chat/Chat.ts
> +    // debugger;
Удаляйте неиспользуемый код из репозитория, он затрудняет чтение

2022-07-17 00:18 UTC, anikogo commented
Отработал по замечаниям
- исправлена проблема с рефрешем страниц на express js
- исправлена проблема с дублированием сообщений
- добавлен функционал редактирования участников чата (добавление/удаление участников)
- у пользователей добавленных в чат при попытке удаления чата выводится сообщение о том, что только создатель чата может удалить его
- в потенциальную кнопку div добавлен role="button"
- убраны лишние комментарии и консоль логи
- статичные УРЛы вынесены отдельно от кода
- добавлена проверка try catch на попытки распарсить ответы с бэкенда

2022-07-17 10:59 UTC, merged